In [1]:
import pandas as pd 
path = "../data/raw/TCGA.LUAD.sampleMap_HiSeqV2.gz"

expr_head = pd.read_csv(
    path,
    sep="\t",
    compression="gzip",
    nrows = 5,
)

expr_head

,sample,TCGA-69-7978-01,TCGA-62-8399-01,TCGA-78-7539-01,TCGA-50-5931-11,TCGA-73-4658-01,TCGA-44-6775-01,TCGA-44-2655-01,TCGA-44-3398-01,TCGA-62-8397-01,...,TCGA-75-7025-01,TCGA-55-7726-01,TCGA-L9-A743-01,TCGA-86-8358-01,TCGA-55-6972-01,TCGA-55-7727-01,TCGA-91-6831-01,TCGA-MN-A4N4-01,TCGA-55-8302-01,TCGA-MP-A4TK-01
0,ARHGEF10L,9.9898,10.4257,9.6264,8.6835,9.2078,10.0039,9.3263,9.0249,10.5411,...,10.0905,7.5219,9.6563,9.2042,8.2127,7.2428,8.8388,9.9341,10.1696,10.1272
1,HIF3A,4.2598,11.6239,9.1362,9.4824,5.0288,4.0573,5.5335,5.7347,6.6477,...,8.0944,4.2952,5.1675,9.2442,9.0641,7.5416,3.5613,8.3457,5.5364,10.2122
2,RNF17,0.4181,0.0000,1.1231,0.8221,0.0000,1.0069,0.6021,0.0000,0.0000,...,0.4628,0.0000,0.9593,0.7339,1.0987,0.9392,0.0000,0.9715,0.0000,0.5804
3,RNF10,10.3657,11.5489,11.6692,11.7341,11.6209,11.1721,11.9169,11.3274,12.3611,...,11.3260,12.0388,11.4458,11.5642,11.5881,11.8686,12.2704,11.8150,11.7813,11.4430
4,RNF11,11.1718,11.0200,10.4679,11.6787,11.3414,11.0969,11.4044,11.4975,11.2828,...,10.8121,11.3304,10.4473,10.9991,10.0014,11.2862,11.1187,10.6101,10.5163,11.1243

In [2]:
expr_head.shape

(5, 577)

In [4]:
expr_head.columns[:10]

Index(['sample', 'TCGA-69-7978-01', 'TCGA-62-8399-01', 'TCGA-78-7539-01',
       'TCGA-50-5931-11', 'TCGA-73-4658-01', 'TCGA-44-6775-01',
       'TCGA-44-2655-01', 'TCGA-44-3398-01', 'TCGA-62-8397-01'],
      dtype='str')

In [5]:
expr_head.iloc[: , :6]

,sample,TCGA-69-7978-01,TCGA-62-8399-01,TCGA-78-7539-01,TCGA-50-5931-11,TCGA-73-4658-01
0,ARHGEF10L,9.9898,10.4257,9.6264,8.6835,9.2078
1,HIF3A,4.2598,11.6239,9.1362,9.4824,5.0288
2,RNF17,0.4181,0.0000,1.1231,0.8221,0.0000
3,RNF10,10.3657,11.5489,11.6692,11.7341,11.6209
4,RNF11,11.1718,11.0200,10.4679,11.6787,11.3414

In [6]:
sample_ids = expr_head.columns[1:]

def sample_type(sample_id: str) -> str:
    code = sample_id.split("-")[-1]
    
    if code == "01":
        return "tumor"
    elif code == "11":
        return "normal"
    else:
        return "other"

labels = pd.DataFrame({
    "sample_id": sample_ids,
    "sample_type": [sample_type(s) for s in sample_ids],
})

labels.head()

         sample_id sample_type
0  TCGA-69-7978-01       tumor
1  TCGA-62-8399-01       tumor
2  TCGA-78-7539-01       tumor
3  TCGA-50-5931-11      normal
4  TCGA-73-4658-01       tumor

In [7]:
labels["sample_type"].value_counts()

sample_type
tumor     515
normal     59
other       2
Name: count, dtype: int64